# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'CDMG-Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CDMG-Project
  pod 'SnapKit', '~> 5.6'


end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    # some older pods don't support some architectures, anything over iOS 11 resolves that
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
